name: Call Reusable Workflow
on:
  push:
    branches:
      - main
      - master

jobs:
  use-reusable:
    uses: assi-w2s/2402-git-repo/.github/workflows/reusable-test.yaml@main
    with:
      cool_var: "amazing"